version: '3.5'

services:
  postgres:
    image: 'postgres:13.1-alpine'
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=changeme
    volumes:
      - ./custom/mount:/var/lib/postgresql/data